baseurl = "https://eclipsefdn-eclipsecon-archive.netlify.com/"
DefaultContentLanguage = "en"
title = "eclipsecon.org"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = "UA-910670-30"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = ""
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = [""]
# logo = "
# styles = ""
# favicon = ""
# share_img = ""
  gcse = "011805775785170369411:p3ec0igo0qq"
#  js = ""

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true